# Imagen base
FROM node:18-alpine

# Instalar dependencias del sistema si son necesarias
RUN apk add --no-cache git

# Directorio de trabajo
WORKDIR /app

# Copiamos los archivos de dependencias primero (mejor cache)
COPY package*.json ./

# Instalamos dependencias
RUN npm install

# Copiamos el resto del proyecto
COPY . .

# Exponemos el puerto 3000
EXPOSE 3000

# Comando por defecto
CMD ["npm", "start"]