# Imagen base de Node.js
FROM node:18-alpine

# Directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias (incluye nodemon para dev)
RUN npm install

# Copiar el resto del código
COPY . .

# Exponer el puerto 4242
EXPOSE 4242

# Comando de desarrollo con nodemon
CMD ["npm", "run", "dev"]